### ISSUE TITLE
SCSS won't build 

### ISSUE THREAD

**Issue by ViktorNova** [davedew/atomik_theme_clone#2]
Fresh clone of the repo, followed all instructions, and the SCSS build is failing: 

```
ERROR in ./assets/scss/presets/default/main.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: ("primary": #2D7AC0, "secondary": #676D6F, "success": #04AF7A, "info": #20BFF0, "warning": #F0B720, "danger": #A32C0D, "light": #F3F3F3, "dark": #373A3B, "light-accent": #9BA5B0, "accent": #F14A20, "dark-accent": #014357) isn't a valid CSS value.
   ╷
88 │ $theme-colors-rgb: map-loop($theme-colors, to-rgb, "$value");
```
same error in assets/scss/presets/rustic-elegance/main.scss

Using Node 18 on Ubuntu 22.04

Any idea what's up? Thanks!

**Comment by davedew** [comment]
Sorry to say, but due to a career change I’m not maintaining this repo. My guess is dependencies might have changed or something with the newer version of node you are using.

**Comment by ViktorNova** [comment]
Gotchya, thanks for your response. Looks like it may have to do with upstream changes in Bedrock and/or Bootstrap-related packages
