### ISSUE TITLE
PR#3 accidentally brought in a bunch of random style changes

### ISSUE THREAD

**Issue by ViktorNova** [davedew/atomik_theme_clone#4]
Hey I know you're not maintaining this anymore and so I'm sorry to bug you again - thank you for merging my pull request to fix the broken build. It looks like a bunch of other random sloppy style commits I made on my fork _after_ I opened the PR got merged in as well -oopsy! This was my fault for doing it all on Master 

Anyway, if you get a minute, reverting to 3796225 (my commit that fixed the build) would fix it, and might help a bunch of people out as this repo is still fairly prominent
Thanks for your time!

**Comment by davedew** [comment]
Ok I reverted those, let me know if that works.

**Comment by ViktorNova** [comment]
It's perfect, thank you!
